# -*- coding: utf-8 -*-
"""calculadora3numero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xMbt4M-zvyzwzjl0sHXoT1PLh9-4_2-
"""

num1 = int(input("ingrese un numero"))
num2 = int(input("ingrese un numero"))
num3 = int(input("ingrese un ultimo numero"))

while True:
  print("menu de opcion")
  print("1-sumar")
  print("2-restar")
  print("3-dividir")
  print("4-multiplicar")
  opc =int(input("ingrese una opcion: "))
  if opc == 1:
    print("la suma es: ", num1 + num2 + num3)
    break
  if opc ==2:
    print("la resta es: ", num1 - num2 - num3)
    break
  if opc ==3:
    print("la division es: ", num1 / num2 / num3)
    break
  if opc ==4:
    print("la multiplicacion es: ", num1 * num2 * num3)
    break